language: android
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
  global:
  - secure: muKrGGAf5UA4DC/IlcZxdgGCMkhlIf6h85LaKZwc2MkMw++YwohdeLds5/NBnSKDjs9D82uVbRiXoFPAj168DMxZA9x0y78Azx4vpmSbZ/WUasa20O1MZM9hF12Vaq2blxpZdSYKh15XrM5Dl1h91nYoaCvoOZBQHiqK80o1SBGX25FYsWtZTpK7cWySkzbc99gJa/owVsjsZ3OTpHegEQ0UlUtuAoMipk9XTDRaH64HbWcVZgvTpG6Kbigoz+6bk6iPdye4cwf9ch4IZPjb0lWTmcJqXB4u79aPCcuTLx6D0Wt74VUGG/qHDaXFDGyIo+n/P1HpNGQVxqqmxIBoNWx1++Kpmi7h5YMO7nrIAXK4yCqQ1DRjLw5endBsT8Oue6eD8aGD/ESMjhzuVXLHl7LIE5wj7KrrTe7q8jTixJ85eYlFvxFEtHLOmWeRtVnORC2dYg9/aleSRuMO+WJKJmfb+71OzVCQl0YeI4zNnt5ER8lbjs0SqZ4nW5d0shfdvreagw53Sup7+/LhnAAXORXp8gW5CG2c5sVmRKHb4NK70up/NdkY1gjqiHprfkPpQ/uJ9RqdIG5aCJAdlT77rHnZ6RPPEJyr+hDxLWCjqeY9Q0ptAiw2QT7hmSXklPnD372SRv5xmpKmFPlMvfsE059HlnzX1dKhUNLomYtZ0Vs=
  - secure: EAp9VhsTQOSvorlVRNYLGDWsc7V9z0lf2VkMddYodSLbGeFG/tkQpv4N/HZw1BtzFnS4saD5GpClPRMhxTYfgG1kBEwTPtvHrN0nio0Jv4Qdw2A34DYsOMino+RSM/Q1oHpcs6D3QjfNLsXuQyM+qdtOG/XmrURA0Uv5mPQfzJ0Au+ElS7+MjrkSviHk0QDUW6xzFVW5qAVZiw5tLAVFSlNcVnVjWEPwgebj+CDmhiIKXRZW+9kFFjuLIYsqhUoFUKfLkxkdaR94MBbNEOGj1/O6i9ueshsuwZuGEZp6OiqGpeHH3x77l4Hw/Qm5Bvz/GaxA7xf9FA86UShzcalhtQUfGiSVsEf4F3FE0iyYK+z370k/qWD2MBKlk7vy8InFdGZK3ohslFU7T4K5drBnUoPdqVOzdQccdO3cpaJ6h34r2s75pmOOx8i3cslEr6YhuqdVLEWG8wgoqV0RjyqYhCgncWH9AtaiFtiwqpFhWjQfbwg1/UPm94Oi6fIBjFJug5/qH1h4J/HQA8lT2kWc1tLAY4hdhmwO0lTMv7g1kpVRY/b/igDkvGjWXmtHoLC9UKJKHT1562igHm4HRZLxF3/9ENw9AfdwgvzMdsqX9Qntce5ka33vfx3GwGKNzkMQ23A0vN5aWpe02bwreuAWlqWp3msVMUs99J+BRWJMH1I=
  - secure: luiGj0qkvl3ziDBJkbnPoV7Pz25xfKcXmRvDkk5sw2KXcGBdH+DMWGW4hbZsXlKBwBFhTrRgCyhONfJkbib4S1o2zd0A/22ldWpWjggIAPPr3VHLW82V/V9krDgheeH8kyfTs8OPNgAXye4NOKMqm63naaVVGa6u/2gZn+P6j0UTgJaQ3srqflWx3I7rYKWOHo+IKQfMzaT47TjpUYPK8kFPFIfhSw/kc6pCYgfVPGI2jckcAn9U9cN6DlW+PO16No/up9BIqz2FBc7V/4kpu9K8Pj1/pyaDBglYH6Piyvvxk8+lyDpZjyMMd0zTYYO4mO5N2fJVbZB1ZgIBogzI51wfV3ZZmLo4HFaHx5/OjuOTV+ANIFc6SOD8OABtKV8fjEDUaSaEDfkheFZZfngFPcu4QPTnW/jYQXIxiHI67N9xeURKE5sAgHxmRvXWwRexLa9wu2Ey/AOh6SUpgzR81EkiSnj4NevOL+5JyRIBCtU1dMb0oBfG10QErCFyhSMzPmNzljGb2y5vEg4FMV/CUCsJogiC6LVNufKsvyW5DWX3PGo7vb99VVoYyzoXNpdjrhs1ex0mqkJXHMN1U8W4nImcZ+6mK2f1yLGyRdbZ8pzsP1eIy+DBiMeuHjOnvTLJBmd1REOboINmvXlLHmlb4o5aawLanmAwAigiX6Ve4GQ=
  - secure: iP8gvyXk9ntbn6eqv17uA0E1HWGZkVTyeQGZ/PkJ2RipBP8sX8wlLkBwreiq/+uvnFUyAx7ckRtcSu1cNTZ636X+3PxV1vi0nym7Q3rp6ASObO+HQho7NEHM64Eo2Bn25XebnVH2fbrDIz/+9a7LyoKBvurL56bj6EoSLZhYwEjMkAjeNigR1HIOEi1GWa1MpueVWFRdWSgDhH6Vk1IIqg6E5YHMvio65hArh39eTxXeVg3OldnGsgxWCYlBeHHKtcbLX7y+niqIEn4Yd336K3x8az1FJJOWgZSFIOO0V+qn1FhRQmSdjYnCly5vSNsdIEmRFY6FUIvli1E7iObw7Nf3usKgTvsliDFDzp9qO8WkoCbQLyXa8wJIJ7k2lhZuAbHCu77rspp+Cd2KeihY6qXcc7w9n14xyHVLIObCl+w+w/MjzYfM/5TK8KOyEE8rUdbDNqwnKRXLBevIs0hkqvM/fYmSQ0oe+iHxa1dqoEjEOcUC3QJawdNo6l7fgHym7MMOCrOUb/IiKQyZ4m8pxCNOMpkfvajIZZy3gXFZ5NL3dcMuGSvB6z4ZzlUTYLJPYDrrAWYT5zohcfTbH+5rcGot82A812EoNPJX+voD0xhRa2RE3+3paIRLWthy+aZyxsANHQgApaMv5bWt+fj+P5wSphntRaxQbj5dBfdXjPg=
  - secure: mK/h/5bY1iFK4UGvcxFdCadRcDdHz4JuJWIf/yf/vszGUS6DUSt+rLcHgJaEq22BCO2cfKTLVwXxfkgxQwcfp4R5a/8kOXE8H/iACQqKe9cbP9U30gZPjvFgAvcy791F/KYNzERNEzy+mfV0hMzG1l1VP6ORZcGGDMeiR/t63UQM5t7SptyUpNW2O87ckBoN8HFYD/+BaY4Xvp6S5UGYWCeOwk48X0ZyIdalhSFTHB4wavl8v7hrlv3KYXp0Xxkf6UTiSbPt/wq3GM1ISmLp4O39dxwl2vo2lQ9vLKCxnNOVhZGJFtIVGiMiawTQex7gCLxDlXp/iii4DLXMWnv4jD8mvauMfZPa3ov5rclCELipNRfLvUMIYguQ+wlm7vd0zJPHRkYZYru6lHKuwXvwezus76One8r8q54Z2REplaeJ/1UTmegNrUieYYvPO3qja25v/9wtdFUxh2pWQ7EmREKhqFsKyqZiRKtb71LtHYfVybJeHf/c/zecmoPoVU45FkW7RaXkjhXx+73NrCKrIK7XeKU5im6jRS6o5VLe4sCTS2TQf/1GmhgUPkzwp0Fvwy6eP+9EKCLMtm7gl+Lk/4yEhashcXSsqF4jUemlwQU2/PHY//LrtK23h5wFd882qUyzJr9lZq+ik9EobLYa1ax08GmKa12GRt/Crpxr5h8=
  - secure: S5GmHd+4JjQphmC95TWw5dMFeTfKT8wWv93bAfsWVOZ2pJufoRt8iuv84jOAmBYF4JtA9wBNDICN7NJBuTlcQQPNCO4otlnUczagmSyQaWXxc/S/WKeQwROdoab6DEeZqLBf3Rr0p3KeBIx/MRhjcJHZIn+W7zukXS8ItpG0z9gUF/7OsYDzPrXWuTX5zKW1zpcCnOOzsx/5seZbRjcEjpPfwyODVpjEF40m5pMOWKfANPeFOWrnSqDYX77DpUFPnUqQVb+bTXSmO+Fl5qp/yXAe4RpOEcjq+HycunKO7q/83yhuIuqEHNuVa1h5JTS5isYbyOc0aA8lXoWJpvIh8w8sx5XPekufzuEBUsa09pJVWtylVHq+UH8R6paB+2UH9u5592fUShhM5SLEqmTi5YkVEhDq2uEAWBSV+Z+26rDd8+txYoIbJ2ulEmLgmi1AnZiQNkvJH1FjN5qH6Fkzf1RMXK9b5I111hek8bgFxAtjtMSMP59dAp5Nq+BBvuh/l8Pm4fxEwZ8uA+9dKsxQedtCWn7KcFBoLLlfpyGerm4BONGJPAPqySxAQ/u3caMmbarYs2jVrbfq4fvIU4R1JbfMxOE1kxVO9/bjwePgtWvMJi/7jNmpXHgqNHhTNAZFwrNpwJFYzZWibHNAyVCWRd7R1iFtgwDvnT4/VGrmhhs=
android:
  components:
  - platform-tools
  - build-tools-23.0.1
  - android-23
  - tools
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
git:
  submodules: false
before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo "sdk.dir=$ANDROID_HOME" > local.properties
- echo yes | android update sdk --all --filter build-tools-23.0.1 --no-ui --force
  > /dev/null
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- sudo apt-get update -qq
- sudo apt-get install -y python2.7
script: "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "app/build/outputs/apk/app-release.apk"
  skip_cleanup: true
  on:
    tags: true
